include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = GitDiff

GitDiff_OBJC_FILES = AppDelegate.m main.m
GitDiff_OBJC_LIBS = -lGitUpKit
GitDiff_RESOURCE_FILES = Base.lproj/MainMenu.xib

# ARC
GitDiff_OBJCFLAGS += -fobjc-arc -fobjc-weak

include $(GNUSTEP_MAKEFILES)/application.make