include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = GitY

GitY_OBJC_FILES = AppDelegate.m Document.m DocumentController.m main.m
GitY_OBJC_LIBS = -lGitUpKit
GitY_RESOURCE_FILES = CommitViewTemplate.png HistoryViewTemplate.png Base.lproj

include $(GNUSTEP_MAKEFILES)/application.make